**Lab 1**

In [1]:
import numpy as np

nparray = np.array([1,2,3,4,5])


In [2]:
print(nparray)

[1 2 3 4 5]


**Create a Numpy array of size 4 x 5.**

In [3]:
npmatrix = np.array([nparray,nparray,nparray,nparray,nparray])

In [4]:
print(npmatrix)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


**Get the Transpose of the Matrix that you created.**

In [5]:
print("Original Matrix 4x5:")
print(npmatrix)
print("Transpose of Matrix 5x4:")
print(npmatrix.T)

Original Matrix 4x5:
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
Transpose of Matrix 5x4:
[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]


**Create a square matrix and find its determinant.**

In [6]:
npmatrix1 = np.array([[1,2,4],
                      [4,7,6],
                      [2,8,10]])

In [7]:
np.linalg.det(npmatrix1)

37.99999999999999

**Create another matrix of size 5 x *4* and randomly initialize it.**

In [8]:
npmatrix2 = np.array([[3,6,7,2],
                      [10,5,25,18],
                      [2,6,9,4],
                      [6,9,12,21],
                      [1,35,13,15]])
npmatrix3 = np.array([[1,3,6,7,2],
                      [35,10,5,25,18],
                      [13,2,6,9,4],
                      [15,6,9,12,21]])

In [9]:
result = np.array([[0,0,0,0],
                   [0,0,0,0],
                   [0,0,0,0],
                   [0,0,0,0],
                   ])


**Perform Matrix multiplication.**

In [10]:
result = np.dot(npmatrix2,npmatrix3)
 
for r in result:
    print(r)

[334  95 108 258 184]
[780 238 397 636 588]
[389 108 132 293 232]
[792 258 342 627 663]
[1620  469  394 1179  999]


**Perform element wise matrix multiplication.**

In [11]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]
              ])

b = np.array([[12,11,3],
              [4,9,6],
              [5,10,6]
              ])

In [12]:
print(a*b)

[[12 22  9]
 [16 45 36]
 [35 80 54]]


**Find mean, median of the numpy array created.**

In [13]:
mean = np.mean(b)
median = np.median(b)

print(mean)
print(median)

7.333333333333333
6.0


 **Obtain each row in the second column of the array.**

In [14]:
for i in range(3):
  print(npmatrix1[i][1])


2
7
8


**Convert Numeric entries(columns) of Iris.csv to Mean Centered Version**

In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')
data=pd.read_csv('/content/drive/My Drive/Iris.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [16]:
print(data - np.mean(data,axis=0))

       Id  PetalLengthCm  PetalWidthCm  SepalLengthCm  SepalWidthCm Species
0   -74.5      -2.358667     -0.998667      -0.743333         0.446     NaN
1   -73.5      -2.358667     -0.998667      -0.943333        -0.054     NaN
2   -72.5      -2.458667     -0.998667      -1.143333         0.146     NaN
3   -71.5      -2.258667     -0.998667      -1.243333         0.046     NaN
4   -70.5      -2.358667     -0.998667      -0.843333         0.546     NaN
..    ...            ...           ...            ...           ...     ...
145  70.5       1.441333      1.101333       0.856667        -0.054     NaN
146  71.5       1.241333      0.701333       0.456667        -0.554     NaN
147  72.5       1.441333      0.801333       0.656667        -0.054     NaN
148  73.5       1.641333      1.101333       0.356667         0.346     NaN
149  74.5       1.341333      0.601333       0.056667        -0.054     NaN

[150 rows x 6 columns]


**Study about numpy array attributes and implement it on the first matrix.**

In [17]:
print("Original Matrix:")
print(npmatrix2)
print("Reshape Matrix:")
print(npmatrix2.reshape(4,5))
print("Shape : ", npmatrix2.shape)
print("Array with elements in range: ")
a1 = np.arange(10)
print(a1)
a1.ndim
print("ItemSize: ",a1.itemsize)
print("Data type of a1: ",a1.dtype)

Original Matrix:
[[ 3  6  7  2]
 [10  5 25 18]
 [ 2  6  9  4]
 [ 6  9 12 21]
 [ 1 35 13 15]]
Reshape Matrix:
[[ 3  6  7  2 10]
 [ 5 25 18  2  6]
 [ 9  4  6  9 12]
 [21  1 35 13 15]]
Shape :  (5, 4)
Array with elements in range: 
[0 1 2 3 4 5 6 7 8 9]
ItemSize:  8
Data type of a1:  int64
